import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "tech-1",
    title: "Titanium Shield iPhone 15/16 Pro Case",
    description: "Engineered from aerospace-grade titanium alloy with shock-absorbing TPU inner bumper. Features tactile metallic buttons and MagSafe 15W alignment.",
    price: 2999,
    discountPrice: 2499,
    imageUrl: "/assets/images/titanium-case.png",
    category: "Phone Cases",
    isBestSeller: true,
    discountTag: "BESTSELLER",
    stock: 25,
    isActive: true,
    createdAt: Date.now() - 100000,
    updatedAt: Date.now() - 50000,
  },
  {
    id: "tech-2",
    title: "Aluminum Dual MagSafe Wireless Charger",
    description: "Minimalist CNC-machined aluminum wireless charging stand. Simultaneously powers your iPhone, Apple Watch, and AirPods with 15W fast charging output.",
    price: 3999,
    discountPrice: 3299,
    imageUrl: "/assets/images/magsafe-charger.png",
    category: "Chargers & Power",
    isBestSeller: true,
    discountTag: "POPULAR",
    stock: 18,
    isActive: true,
    createdAt: Date.now() - 90000,
    updatedAt: Date.now() - 40000,
  },
  {
    id: "tech-3",
    title: "Tempered Privacy Glass Protector (2-Pack)",
    description: "9H hardness 2-way privacy screen filter blocks side angles beyond 28 degrees. Includes alignment tray for bubble-free zero-error application.",
    price: 1299,
    discountPrice: 999,
    imageUrl: "/assets/images/titanium-case.png",
    category: "Screen Protection",
    isBestSeller: false,
    discountTag: "SAVER",
    stock: 40,
    isActive: true,
    createdAt: Date.now() - 80000,
    updatedAt: Date.now() - 30000,
  },
  {
    id: "tech-4",
    title: "Custom 3D Texture Carbon Fiber Skin",
    description: "Precision laser-cut 3M vinyl skin providing scratch protection and enhanced tactile grip without adding bulk. Air-release adhesive guarantees zero bubbles.",
    price: 1099,
    discountPrice: 899,
    imageUrl: "/assets/images/hero-banner.png",
    category: "Custom Skins",
    isBestSeller: false,
    discountTag: "NEW",
    stock: 30,
    isActive: true,
    createdAt: Date.now() - 70000,
    updatedAt: Date.now() - 20000,
  },
  {
    id: "tech-5",
    title: "Heavy-Duty Braided Fast Charging Cable (2m)",
    description: "Reinforced Kevlar-braided USB-C to USB-C 100W PD charging cable. Rated for 30,000+ bends with LED power status indicator.",
    price: 899,
    discountPrice: 699,
    imageUrl: "/assets/images/magsafe-charger.png",
    category: "Cables & Adapters",
    isBestSeller: true,
    discountTag: "ESSENTIAL",
    stock: 50,
    isActive: true,
    createdAt: Date.now() - 60000,
    updatedAt: Date.now() - 10000,
  }
];
